Blog_Web/Blog_Web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls', namespace="main"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    

Blog_Web/main/urls.py
from django.urls import path
from . import views

app_name = "main"

#creando los path correspondientes para interactuar con la aplicacion
#por medio de views

urlpatterns = [
    #registro y logeo de usuarios
    path('register/',views.registerPage, name="register"),
    path('login/', views.loginPage, name="login"),
    path('logout/',views.logoutUser, name="logout"),
    path('contact/', views.ContactView.as_view(), name="contact"),

    #indice de la aplicacion
    path('',views.IndexView.as_view(),name="home"),

    #Reviews
    path('reviewsaddinfo/', views.ReviewsAddInfo.as_view(), name="reviewsaddinfo"),
    path('reviews/', views.ReviewsView.as_view(), name="reviews"),
    path('reviews/<slug:slug>',views.ReviewsDetailView.as_view(), name="review"),
    #Blogs
    path('blogaddinfo/', views.BlogAddInfo.as_view(), name="blogaddinfo"),
    path('blog/', views.BlogView.as_view(), name="blogs"),
    path('blog/<slug:slug>', views.BlogDetailView.as_view(), name = 'blog'),
    path('portfolio/', views.PortfolioView.as_view(), name="portfolio"),
    path('portfolio/<slug:slug>', views.PortfolioDetailView.as_view(), name = "portfolio"),
    

]

Blog_Web/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from ckeditor.fields import RichTextField

#creando las tablas en las que se guardara la informacion de nuestra aplicacion


class UserProfile(models.Model):

    class Meta:
        verbose_name_plural = 'User Profiles'
        verbose_name = 'User Profile'
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(blank=True, null=True, upload_to="avatar")
    title = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    cv = models.FileField(blank=True, null=True, upload_to="cv")

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'


class ContactProfile(models.Model):
    
    class Meta:
        verbose_name_plural = 'Contact Profiles'
        verbose_name = 'Contact Profile'
        ordering = ["timestamp"]
    timestamp = models.DateTimeField(auto_now_add=True)
    name = models.CharField(verbose_name="Name",max_length=100)
    email = models.EmailField(verbose_name="Email")
    message = models.TextField(verbose_name="Message")

    def __str__(self):
        return f'{self.name}'


#Tabla destinada al almacenamiento de archivos multimedia
class Media(models.Model):

    class Meta:
        verbose_name_plural = 'Media Files'
        verbose_name = 'Media'
        ordering = ["name"]
	
    image = models.ImageField(blank=True, null=True, upload_to="media")
    url = models.URLField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    is_image = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if self.url:
            self.is_image = False
        super(Media, self).save(*args, **kwargs)
    def __str__(self):
        return self.name

#Tabla destinada a almacenar los portafolios
class Portfolio(models.Model):

    class Meta:
        verbose_name_plural = 'Portfolio Profiles'
        verbose_name = 'Portfolio'
        ordering = ["name"]
    date = models.DateTimeField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    image = models.ImageField(blank=True, null=True, upload_to="portfolio")
    slug = models.SlugField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Portfolio, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/portfolio/{self.slug}"

#Tabla destinada a almacenar los Blogs
class Blog(models.Model):

    class Meta:
        verbose_name_plural = 'Blog Profiles'
        verbose_name = 'Blog'
        ordering = ["timestamp"]

    timestamp = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=200, blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    slug = models.SlugField(null=True, blank=True)
    image = models.ImageField(blank=True, null=True, upload_to="blog")
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Blog, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/blog/{self.slug}"

#Tabla destinada a almacenar las reviews
class Reviews(models.Model):

    class Meta:
        verbose_name_plural = 'Reviews Profiles'
        verbose_name = 'Reviews'
        ordering = ["timestamp"]

    timestamp = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=200, blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    slug = models.SlugField(null=True, blank=True)
    image = models.ImageField(blank=True, null=True, upload_to="reviews")
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Reviews, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/reviews/{self.slug}"

    


Blog_Web/main/forms.py
from importlib.metadata import requires
from django import forms
from .models import Blog, ContactProfile, Reviews

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

#Registro de los forms que tomaran la informacion ingresada en la aplicacion


class ContactForm(forms.ModelForm):

	name = forms.CharField(max_length=100, required=True,
		widget=forms.TextInput(attrs={
			'placeholder': '*Full name..',
			}))
	email = forms.EmailField(max_length=254, required=True, 
		widget=forms.TextInput(attrs={
			'placeholder': '*Email..',
			}))
	message = forms.CharField(max_length=1000, required=True, 
		widget=forms.Textarea(attrs={
			'placeholder': '*Message..',
			'rows': 6,
			}))


	class Meta:
		model = ContactProfile
		fields = ('name', 'email', 'message',)
#Form encargado de crear nuevos usuarios 
class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

#Form encargado de crear nuevos blogs desde la propia aplicación
class BlogForm(forms.ModelForm):

	author = forms.CharField(max_length=200, required=True,
		widget=forms.TextInput(attrs={
		'placeholder': '*Author name...',
	}))
	name = forms.CharField(max_length=200, required=True,
		widget=forms.TextInput(attrs={
		'placeholder': '*Full name...',
	}))
	description = forms.CharField(max_length=500, required=True,
		widget=forms.TextInput(attrs={
		'placeholder': '*Description...',
	}))
	body = forms.CharField(max_length=1000, required=True,
		widget=forms.Textarea(attrs={
		'placeholder': '*Body info...',
	}))
	image = forms.ImageField()

	class Meta:
		model = Blog
		fields =['author','name', 'description', 'body', 'image']

#Form encargado de crear nuevas reviews desde la misma aplicacion
class ReviewsForm(forms.ModelForm):

	author = forms.CharField(max_length=200, required=True,
		widget=forms.TextInput(attrs={
		'placeholder': '*Author name...',
	}))
	name = forms.CharField(max_length=200, required=True,
		widget=forms.TextInput(attrs={
		'placeholder': '*Full name...',
	}))
	description = forms.CharField(max_length=500, required=True,
		widget=forms.TextInput(attrs={
		'placeholder': '*Description...',
	}))
	body = forms.CharField(max_length=1000, required=True,
		widget=forms.Textarea(attrs={
		'placeholder': '*Body info...',
	}))
	image = forms.ImageField()

	class Meta:
		model = Reviews
		fields =['author','name', 'description', 'body', 'image']

Blog_Web/main/views.py
from multiprocessing import context
from django.shortcuts import render

#
#importaciones necesarias 
from django.shortcuts import render
from django.contrib import messages
from .models import (
		UserProfile,
        Portfolio,
        Blog,
        Reviews,
	)

from django.views import generic
from . forms import BlogForm, ContactForm, ReviewsForm, CreateUserForm

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse
from django.shortcuts import redirect

#registro de usuarios
def registerPage(request):
	if request.user.is_authenticated:
		return redirect("main:home")
	else:
		form = CreateUserForm()
		if request.method == 'POST':
			form =CreateUserForm(request.POST)
			if form.is_valid():
				form.save()
				user = form.cleaned_data.get('username')
				messages.success(request, 'La cuenta fue creada con el nombre: '+ user)

				return redirect('main:register')
		
		context = {'form':form}
		return render(request, 'main/register.html', context)

#Logeo de usuarios
def loginPage(request):
	if request.user.is_authenticated:
		return redirect("main:home")
	else:
		if request.method == 'POST':
			username = request.POST.get('username')
			password = request.POST.get('password')

			user = authenticate(request, username=username, password=password)

			if user is not None:
				login(request, user)
				return redirect("main:home")
			else:
				messages.info(request, 'Username OR Password is incorrect')
		context = {}
		return render(request, 'main/contact.html', context)

#Cerrar sesion de usuarios
def logoutUser(request):
	logout(request)
	return redirect('main:contact')
		


#indice de la aplicacion
class IndexView(generic.TemplateView):
	template_name = "main/index.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		
		reviews = Reviews.objects.filter(is_active=True)
		blogs = Blog.objects.filter(is_active=True)
		portfolio = Portfolio.objects.filter(is_active=True)
		
		context["reviews"] = reviews
		context["blogs"] = blogs
		context["portfolio"] = portfolio
		return context


class ContactView(generic.FormView):
	template_name = "main/contact.html"
	form_class = ContactForm
	success_url = "/"
	
	def form_valid(self, form):
		form.save()
		messages.success(self.request, 'Gracias por la sugerencia.')
		return super().form_valid(form)

#clase para agregar informacion a los blogs desde la app
class BlogAddInfo(generic.FormView):
	template_name = "main/blog-add.html"
	form_class = BlogForm
	success_url = "/"
	
	def form_valid(self, form):
		form.save()
		messages.success(self.request, 'Gracias por la contribucion a los Bolgs.')
		return super().form_valid(form)
#clase para agregar informacion a las reviews desde la app
class ReviewsAddInfo(generic.FormView):
	template_name = "main/Reviews-add.html"
	form_class = ReviewsForm
	success_url = "/"
	
	def form_valid(self, form):
		form.save()
		messages.success(self.request, 'Gracias por la contribucion a las Reviews.')
		return super().form_valid(form)


class PortfolioView(generic.ListView):
	model = Portfolio
	template_name = "main/portfolio.html"
	paginate_by = 10

	def get_queryset(self):
		return super().get_queryset().filter(is_active=True)


class PortfolioDetailView(generic.DetailView):
	model = Portfolio
	template_name = "main/portfolio-detail.html"
#clase para mostrar los blogs
class BlogView(generic.ListView):
	model = Blog
	template_name = "main/blog-home.html"
	paginate_by = 10
	
	def get_queryset(self):
		return super().get_queryset().filter(is_active=True)

#clase para mostrar los detalles de los blogs
class BlogDetailView(generic.DetailView):
	model = Blog
	template_name = "main/blog-post.html"


#clase para mostrar las reviews
class ReviewsView(generic.ListView):
    model = Reviews
    template_name = "main/reviews-home.html"
    paginate_by = 10 

    def get_queryset(self):
        return super().get_queryset().filter(is_active=True)

#clase para mostrar los detalles de las reviews
class ReviewsDetailView(generic.DetailView):
    model = Reviews
    template_name = "main/reviews-post.html"

Blog_Web/main/templates/main/blog-home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Manga&Blogs--Blogs</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body class="d-flex flex-column h-100">
        <main class="flex-shrink-0">
            <!-- Navigation-->
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div class="container px-5">
                    <a class="navbar-brand" href="{% url 'main:home' %}">Home</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                            <li class="nav-item"><a class="nav-link" href="{% url 'main:home' %}">Home</a></li>

                            <li class="nav-item"><a class="nav-link" href="{% url 'main:contact' %}">Login</a></li>
                          
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdownBlog" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Blog</a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownBlog">
                                    <li><a class="dropdown-item" href="{% url 'main:blogs' %}">Blog Home</a></li>
                                    <li><a class="dropdown-item" href="{% url 'main:blogaddinfo' %}">Blog Add</a></li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdownPortfolio" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Reviews</a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownPortfolio">
                                    <li><a class="dropdown-item" href="{% url 'main:reviews' %}">Reviews Home</a></li>
                                    <li><a class="dropdown-item" href="{% url 'main:reviewsaddinfo' %}">Reviews Add</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- Page Content-->
            <section class="py-5">
                {% for obj in object_list %}
                <div class="container px-5">
                    <h1 class="fw-bolder fs-5 mb-4"></h1>
                    <div class="card border-0 shadow rounded-3 overflow-hidden">
                        
                        <div class="card-body p-0">
                            <div class="row gx-0">
                                
                                <div class="col-lg-6 col-xl-5 py-lg-5">
                                    <div class="p-4 p-md-5">
                                        <div class="badge bg-primary bg-gradient rounded-pill mb-2"></div>
                                        <div class="h2 fw-bolder">{{obj.name}}</div>
                                        <p>{{obj.description}}</p>
                                        <a class="stretched-link text-decoration-none" href="{% url 'main:blog' slug=obj.slug %}">
                                            Read more
                                            <i class="bi bi-arrow-right"></i>
                                        </a>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-xl-7"><div class="bg-featured-blog" style="background-image: url('{{obj.image.url}}')"></div></div>
                               
                            </div>
                        </div>
                       
                    </div>
                </div>
                {% endfor %}
            </section>
            <section class="py-5 bg-light">
                <div class="container px-5">
                    <div class="row gx-5">
                        <div class="col-xl-8">
                            <h2 class="fw-bolder fs-5 mb-4">News</h2>
                            <!-- News item-->
                            <div class="mb-4">
                                <div class="small text-muted">May 12, 2022</div>
                                <a class="link-dark" href="#!"><h3>Start Bootstrap releases Bootstrap 5 updates for templates and themes</h3></a>
                            </div>
                            <!-- News item-->
                            <div class="mb-5">
                                <div class="small text-muted">May 5, 2022</div>
                                <a class="link-dark" href="#!"><h3>Bootstrap 5 has officially landed</h3></a>
                            </div>
                            <!-- News item-->
                            <div class="mb-5">
                                <div class="small text-muted">Apr 21, 2022</div>
                                <a class="link-dark" href="#!"><h3>This is another news article headline, but this one is a little bit longer</h3></a>
                            </div>
                            <div class="text-end mb-5 mb-xl-0">
                                <a class="text-decoration-none" href="#!">
                                    More news
                                    <i class="bi bi-arrow-right"></i>
                                </a>
                            </div>
                        </div>
                        <div class="col-xl-4">
                            <div class="card border-0 h-100">
                                <div class="card-body p-4">
                                    <div class="d-flex h-100 align-items-center justify-content-center">
                                        <div class="text-center">
                                            <div class="h6 fw-bolder">Contact</div>
                                            <p class="text-muted mb-4">
                                                For press inquiries, email us at
                                                <br />
                                                <a href="#!">press@domain.com</a>
                                            </p>
                                            <div class="h6 fw-bolder">Follow us</div>
                                            <a class="fs-5 px-2 link-dark" href="#!"><i class="bi-twitter"></i></a>
                                            <a class="fs-5 px-2 link-dark" href="#!"><i class="bi-facebook"></i></a>
                                            <a class="fs-5 px-2 link-dark" href="#!"><i class="bi-linkedin"></i></a>
                                            <a class="fs-5 px-2 link-dark" href="#!"><i class="bi-youtube"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Blog preview section-->
           
        </main>
        <!-- Footer-->
        <footer class="bg-dark py-4 mt-auto">
            <div class="container px-5">
                <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                    <div class="col-auto"><div class="small m-0 text-white">Copyright &copy; Your Website 2022</div></div>
                    <div class="col-auto">
                        <a class="link-light small" href="#!">Privacy</a>
                        <span class="text-white mx-1">&middot;</span>
                        <a class="link-light small" href="#!">Terms</a>
                        <span class="text-white mx-1">&middot;</span>
                        <a class="link-light small" href="#!">Contact</a>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

Blog_Web/main/templates/main/reviews-home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Manga&Blogs--Reviews</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body class="d-flex flex-column h-100">
        <main class="flex-shrink-0">
            <!-- Navigation-->
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div class="container px-5">
                    <a class="navbar-brand" href="{% url 'main:home' %}">Home</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                            <li class="nav-item"><a class="nav-link" href="{% url 'main:home' %}">Home</a></li>

                            <li class="nav-item"><a class="nav-link" href="{% url 'main:contact' %}">Login</a></li>
                          
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdownBlog" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Blog</a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownBlog">
                                    <li><a class="dropdown-item" href="{% url 'main:blogs' %}">Blog Home</a></li>
                                    <li><a class="dropdown-item" href="{% url 'main:blogaddinfo' %}">Blog Add</a></li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdownPortfolio" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Reviews</a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownPortfolio">
                                    <li><a class="dropdown-item" href="{% url 'main:reviews' %}">Reviews Home</a></li>
                                    <li><a class="dropdown-item" href="{% url 'main:reviewsaddinfo' %}">Reviews Add</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- Page Content-->

            <!-- Blog preview section-->
            <section class="py-5">
                <div class="container px-5">
                    <h2 class="fw-bolder fs-5 mb-4">Reviews</h2>
                    <div class="row gx-5">
                        {% for obj in object_list %}
                        <div class="col-lg-4 mb-5">
                            <div class="card h-100 shadow border-0">
                                <img class="card-img-top" src="{{obj.image.url}}" alt="..." />
                                <div class="card-body p-4">
                                   
                                    <a class="text-decoration-none link-dark stretched-link" href="{% url 'main:review' slug=obj.slug %}"><div class="h5 card-title mb-3">{{obj.name}}</div></a>
                                    <p class="card-text mb-0">{{obj.description}}</p>
                                </div>
                                <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                                    <div class="d-flex align-items-end justify-content-between">
                                        <div class="d-flex align-items-center">
                                            
                                            <div class="small">
                                                <div class="fw-bold">{{obj.author}}</div>
                                                <div class="text-muted">{{obj.timestamp}}</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}

                    </div>
                    <div class="text-end mb-5 mb-xl-0">
                        <a class="text-decoration-none" href="#!">
                            
                           <!-- <i class="bi bi-arrow-right"></i>-->
                        </a>
                    </div>
                </div>
            </section>
        </main>
        <!-- Footer-->
        <footer class="bg-dark py-4 mt-auto">
            <div class="container px-5">
                <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                    <div class="col-auto"><div class="small m-0 text-white">Copyright &copy; Your Website 2022</div></div>
                    <div class="col-auto">
                        <a class="link-light small" href="#!">Privacy</a>
                        <span class="text-white mx-1">&middot;</span>
                        <a class="link-light small" href="#!">Terms</a>
                        <span class="text-white mx-1">&middot;</span>
                        <a class="link-light small" href="#!">Contact</a>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>